// Tests the distribution generated by Java's Math.random() function.
public  class  TestRandom {
	public static void main(String[]  args) 
	{
	    int n = Integer.parseInt(args[0]);
		int i1=0;
		int i2=0;
		for(int i3=0 ;i3<(n-1);i3++)
		{
			if(Math.random()>0.5) i1++;
			else i2++;
		}
		System.out.println("> 0.5: "+ i1);
		System.out.println("<= 0.5: "+ i2);
		System.out.println("Ratio: "+ (double)i1/i2);
	}
}
